# Project information
site_name: Selfedelics
site_description: Do it yourself psychedelics
site_author: Selfedelic

google_analytics:
  - 'UA-151448862-2'
  - 'auto'

# Github repo links
repo_name: 'Selfedelics/selfedelics'
repo_url: 'https://github.com/Selfedelics/selfedelics'


# Navigation
nav:
  - Home: 'index.md'
  - Mushrooms:
    - 'pftek/pftek.md'
  - San Pedro:
    - JTTek: 'sanpedro/jttek.md'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

# Customization
extra:
  manifest: 'manifest.json'
  social:
    - type: 'github'
      link: 'https://github.com/Selfedelics'

extra_javascript:
  - 'javascripts/rsw.js'
