# Project information
site_name: Selfedelics
site_description: Do it yourself psychedelics
site_author: Selfedelic
site_url: https://selfedelics.com

google_analytics:
  - 'UA-151448862-2'
  - 'auto'

# Github repo links
repo_name: 'Selfedelics/selfedelics'
repo_url: https://github.com/Selfedelics/selfedelics


# Navigation
nav:
  - Home: 'index.md'
  - Mushrooms:
    - Intro: 'mushrooms/index.md'
    - 'mushrooms/pftek/index.md'
  - San Pedro:
    - Intro: 'sanpedro/index.md'
    - Fresh Tea Tek: 'sanpedro/fttek.md'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: true

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

# Customization
extra:
  manifest: 'manifest.json'
  disqus: 'selfedelics'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Selfedelics

extra_javascript:
  - 'javascripts/rsw.js'
